server:
  port: 8091

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/contentdb
    username: admin
    password: admin
  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Flyway configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      user: admin
      password: admin
      baseline-description: "Baseline init for user service"
      baseline-version: 0
  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9099/realms/GenEdu
          jwk-set-uri: http://localhost:9099/realms/GenEdu/protocol/openid-connect/certs
# Spring Doc configuration
