server:
  port: 8222
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9099/realms/GenEdu
          jwk-set-uri: http://localhost:9099/realms/GenEdu/protocol/openid-connect/certs
  # Gateway configuration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: false
  # Route configuration
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        # User Service Swagger Route
        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
            - Path=/aggregate/user-service/**
          filters:
            - RewritePath=/aggregate/user-service(?<segment>/?.*), $\{segment}

# Spring Doc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    # Configuration for Swagger UI Services
    urls:
      - name: User Service
        url: /aggregate/user-service/v3/api-docs