server:
  port: ${MEDIA_SERVICE_PORT:8091}

spring:
  # Database configuration
  datasource:
    url: ${POSTGRES_MEDIA_DB_URL}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}

  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Flyway configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      user: ${POSTGRES_USER:admin}
      password: ${POSTGRES_PASSWORD:admin}
      baseline-description: "Baseline init for user service"
      baseline-version: 0
  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9099/realms/GenEdu}
          jwk-set-uri: ${JWT_SET_JWKS_URI:http://localhost:9099/realms/GenEdu/protocol/openid-connect/certs}

# Spring Doc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KC_GENEDU_GENEDU_BE_CLIENT_ID:genedu-be}
      client-secret: ${KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY:0pQYYepE82DkALnEVhAfZREPeHmtHz3z}
    csrf:
      enabled: false

# AWS S3 configuration
aws:
  credentials:
    access-key: test_access_key
    secret-key: test_secret_access_key
  region: us-east-1
  s3:
    endpoint: https://lcs.lch.id.vn/
    bucket:
      name: media-bucket