server:
  port: ${SUBSCRIPTION_SERVICE_PORT:8094}
spring:
  # Database configuration
  datasource:
    url: ${POSTGRES_SUBSCRIPTION_DB_URL}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Flyway configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      user: ${POSTGRES_USER:admin}
      password: ${POSTGRES_PASSWORD:admin}
      baseline-description: "Baseline init for subscription service"
      baseline-version: 0
  # Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9099/realms/GenEdu}
          jwk-set-uri: ${JWT_SET_JWKS_URI:http://localhost:9099/realms/GenEdu/protocol/openid-connect/certs}
  # Gmail configuration
  mail:
    enabled: true
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:shinkirilovforever@gmail.com}
    password: ${EMAIL_PASSWORD:syrrljluormikseh}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Spring Doc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KC_GENEDU_GENEDU_BE_CLIENT_ID:genedu-be}
      client-secret: ${KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY:0pQYYepE82DkALnEVhAfZREPeHmtHz3z}
    csrf:
      enabled: false

# Stripe payment configuration
stripe:
  secretKey: ${STRIPE_SECRET_KEY:sk_test_51RetFgC4VPxDeMTHqlgqwXfhq88J31tyEYuaEk8y2JZBefMzaFm18ALRS2xkxZ7yONrZKXwRjetP000zjqg5FiPF00mjAH1clJ}
  publicKey: ${STRIPE_PUBLIC_KEY:pk_test_51RetFgC4VPxDeMTHfPpc7O4bVzgG27vmT0m0UjkN3TnPUutoAiIzFwxS51L4FiSsI7vBi5RxpnpRf8oZvj1lAR3u00QbwpglKm}
  webhookSecret: ${WEBHOOK_SECRET:whsec_6814338c5b7b02eaafcbd429340ab40010fc0dbddab436eea962ceca45674f03}
  successUrl: ${STRIPE_SUCCESS_URL:http://localhost:8094/stripe/success}
  cancelUrl: ${STRIPE_CANCEL_URL:http://localhost:8094/stripe/cancel}

zone:
  id: ${ZONE_ID:Asia/Saigon}
