server:
  port: ${USER_SERVICE_PORT:8090}

spring:
  # Database configuration
  datasource:
    url: ${POSTGRES_USER_DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}

  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Flyway configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      user: ${POSTGRES_USER:admin}
      password: ${POSTGRES_PASSWORD:admin}
      baseline-description: "Baseline init for user service"
      baseline-version: 0
# Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9099/realms/GenEdu
          jwk-set-uri: http://localhost:9099/realms/GenEdu/protocol/openid-connect/certs
# Spring Doc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KC_GENEDU_GENEDU_BE_CLIENT_ID:genedu-be}
      client-secret: ${KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY:r2zFR2utotgHybjmw1JAXk8TRyYsvvWz-be}
    csrf:
      enabled: false

# Keycloak configuration
keycloak:
  server-url: ${KEYCLOAK_URL:http://localhost:9099}
  realm: ${KEYCLOAK_REALM_NAME:GenEdu}
  client-id: ${KC_GENEDU_ADMIN_CLI_CLIENT_ID:admin-cli}
  grant-type: password
  password: ${KC_GENEDU_ADMIN_CLI_ADMIN_PASSWORD:genedu-admin}
  username: ${KC_GENEDU_ADMIN_CLI_ADMIN_USERNAME:genedu-admin}
  client-secret: ${KC_GENEDU_ADMIN_CLI_GENEDU_SCRET_KEY:wEli51b7nULXyzcNAao2jqu1HEAEJgNw}
