server:
  port: 8090

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: admin
  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Flyway configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      user: admin
      password: admin
      baseline-description: "Baseline init for user service"
      baseline-version: 0
