CREATE TABLE media_files
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name   VARCHAR(255)                            NOT NULL,
    file_type   VARCHAR(255)                            NOT NULL,
    file_url    TEXT                                    NOT NULL,
    uploaded_by UUID                                    NOT NULL,
    uploaded_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_deleted  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_media_files PRIMARY KEY (id)
);