spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service


springdoc:
  swagger-ui:
    oauth:
      client-id: genedu-be
      client-secret: r2zFR2utotgHybjmw1JAXk8TRyYsvvWz
    csrf:
      enabled: false