spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: '*'
              allowedMethods: '*'
              allowedHeaders: '*'
              allowCredentials: false
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
          - Path=/api/v1/users/**
        - id: user-service-swagger
          uri: lb://USER-SERVICE
          predicates:
          - Path=/aggregate/user-service/**
          filters:
          - RewritePath=/aggregate/user-service(?<segment>/?.*), $\{segment}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
    urls:
      - name: User Service
        url: /aggregate/user-service/v3/api-docs
