services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.3
    command: 'start-dev --import-realm'
    ports:
      - 9099:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - microservices-net
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json

  config-server:
    build: ./services/config-server
    container_name: config-server
    image: config-server:latest
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - KC_GENEDU_GENEDU_BE_CLIENT_ID
        - KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY
        - KC_GENEDU_ADMIN_CLI_CLIENT_ID
        - KC_GENEDU_ADMIN_CLI_GENEDU_SCRET_KEY
    networks:
      - microservices-net

  discovery-service:
    build:
      context: ./services/discovery
      dockerfile: Dockerfile
    container_name: discovery
    image: discovery:latest
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8761/eureka/apps"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  gateway-service:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway
    image: gateway:latest
    ports:
      - "8222:8222"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://host.docker.internal:8222/actuator/health"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KC_GENEDU_GENEDU_BE_CLIENT_ID
      - KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - microservices-net

  content-service:
    build:
      context: ./services/content
      dockerfile: Dockerfile
    container_name: content
    image: content:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KC_GENEDU_GENEDU_BE_CLIENT_ID
      - KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY
    ports:
      - "8091:8091"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      gateway-service:
        condition: service_healthy
      keycloak:
        condition: service_started
      postgresql:
        condition: service_started
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: