eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
name:
  value: genEdu
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0