server:
  port: 8090

spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/userdb
    username: admin
    password: admin
  # JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Flyway configuration
    flyway:
      enabled: true
      baseline-on-migrate: true
      user: admin
      password: admin
      baseline-description: "Baseline init for user service"
      baseline-version: 0
# Security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9099/realms/GenEdu
          jwk-set-uri: http://host.docker.internal:9099/realms/GenEdu/protocol/openid-connect/certs
# Spring Doc configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KC_GENEDU_GENEDU_BE_CLIENT_ID:genedu-be}
      client-secret: ${KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY:r2zFR2utotgHybjmw1JAXk8TRyYsvvWz-be}
    csrf:
      enabled: false

# Keycloak configuration
keycloak:
  server-url: http://host.docker.internal:9099
  realm: GenEdu
  client-id: ${KC_GENEDU_ADMIN_CLI_CLIENT_ID:admin-cli}
  grant-type: password
  password: genedu-admin
  username: genedu-admin
  client-secret: ${KC_GENEDU_ADMIN_CLI_GENEDU_SCRET_KEY:wEli51b7nULXyzcNAao2jqu1HEAEJgNw}
