spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: content-service

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${KC_GENEDU_GENEDU_BE_CLIENT_ID:genedu-be}
      client-secret: ${KC_GENEDU_GENEDU_BE_GENEDU_SCRET_KEY:4s8kiGJYTlSXle0J9baOvkfjv27ukAkW}
    csrf:
      enabled: false