FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mvn clean package

FROM openjdk:21-jdk AS runner

WORKDIR /app

COPY --from=builder /app/target/config-server-0.0.1-SNAPSHOT.jar ./config-server.jar

EXPOSE 8888

ENTRYPOINT ["java", "-jar", "config-server.jar"]