CREATE TABLE chapters
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number INTEGER,
    title        VARCHAR(255),
    description  TEXT,
    subject_id   BIGINT,
    CONSTRAINT pk_chapters PRIMARY KEY (id)
);

CREATE TABLE lessons
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    order_number INTEGER                                 NOT NULL,
    description  TEXT,
    chapter_id   BIGINT,
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);

CREATE TABLE school_classes
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description TEXT,
    CONSTRAINT pk_school_classes PRIMARY KEY (id)
);

CREATE TABLE subjects
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     TEXT,
    school_class_id INTEGER,
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

ALTER TABLE chapters
    ADD CONSTRAINT FK_CHAPTERS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE lessons
    ADD CONSTRAINT FK_LESSONS_ON_CHAPTER FOREIGN KEY (chapter_id) REFERENCES chapters (id);

ALTER TABLE subjects
    ADD CONSTRAINT FK_SUBJECTS_ON_SCHOOLCLASS FOREIGN KEY (school_class_id) REFERENCES school_classes (id);