CREATE TABLE "school_classes" (
                                  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "name" varchar(100) NOT NULL,
                                  "description" text,
                                  "created_by" uuid NOT NULL,
                                  "created_on" timestamp NOT NULL,
                                  "last_modified_by" uuid NOT NULL,
                                  "last_modified_on" timestamp NOT NULL,
                                  "is_deleted" bool DEFAULT false
);

CREATE TABLE "subjects" (
                            "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "name" varchar(100) NOT NULL,
                            "description" text,
                            "school_class_id" int,
                            "created_by" uuid NOT NULL,
                            "created_on" timestamp NOT NULL,
                            "last_modified_by" uuid NOT NULL,
                            "last_modified_on" timestamp NOT NULL,
                            "is_deleted" bool DEFAULT false
);

CREATE TABLE "materials" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "title" varchar(150) NOT NULL,
                             "order_number" integer NOT NULL,
                             "description" text,
                             "subject_id" int,
                             "created_by" uuid NOT NULL,
                             "created_on" timestamp NOT NULL,
                             "last_modified_by" uuid NOT NULL,
                             "last_modified_on" timestamp NOT NULL,
                             "is_deleted" bool DEFAULT false
);

CREATE TABLE "chapters" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "material_id" bigint,
                            "title" varchar(150) NOT NULL,
                            "order_number" integer NOT NULL,
                            "description" text,
                            "created_by" uuid NOT NULL,
                            "created_on" timestamp NOT NULL,
                            "last_modified_by" uuid NOT NULL,
                            "last_modified_on" timestamp NOT NULL,
                            "is_deleted" bool DEFAULT false
);

CREATE TABLE "lessons" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "chapter_id" bigint,
                           "title" varchar(150) NOT NULL,
                           "order_number" integer NOT NULL,
                           "description" varchar(255),
                           "status" VARCHAR(20) DEFAULT 'UN_SYNC',
                           "created_by" uuid NOT NULL,
                           "created_on" timestamp NOT NULL,
                           "last_modified_by" uuid NOT NULL,
                           "last_modified_on" timestamp NOT NULL,
                           "is_deleted" bool DEFAULT false
);

CREATE TABLE "lesson_contents" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "lesson_id" bigint,
                                   "title" varchar(150) NOT NULL,
                                   "order_number" integer NOT NULL,
                                   "content" text NOT NULL,
                                   "created_by" uuid NOT NULL,
                                   "created_on" timestamp NOT NULL,
                                   "last_modified_by" uuid NOT NULL,
                                   "last_modified_on" timestamp NOT NULL,
                                   "is_deleted" bool DEFAULT false
);

CREATE TABLE "lesson_content_media_files" (
                                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "lesson_content_id" bigint NOT NULL,
                                              "media_file_id" bigint NOT NULL,
                                              "order_number" integer NOT NULL DEFAULT 0,
                                              "description" text
);

CREATE UNIQUE INDEX "idx_materials_order_number" ON "materials" ("order_number", "subject_id");

CREATE UNIQUE INDEX "idx_chapters_order_number" ON "chapters" ("order_number", "material_id");

CREATE UNIQUE INDEX "idx_lessons_order_number" ON "lessons" ("order_number", "chapter_id");

CREATE UNIQUE INDEX "idx_lecture_contents_number" ON "lesson_contents" ("order_number", "lesson_id");

CREATE UNIQUE INDEX "idx_lecture_contents_media_number" ON "lesson_content_media_files" ("order_number", "lesson_content_id");

ALTER TABLE "subjects" ADD FOREIGN KEY ("school_class_id") REFERENCES "school_classes" ("id");

ALTER TABLE "materials" ADD FOREIGN KEY ("subject_id") REFERENCES "subjects" ("id");

ALTER TABLE "chapters" ADD FOREIGN KEY ("material_id") REFERENCES "materials" ("id");

ALTER TABLE "lessons" ADD FOREIGN KEY ("chapter_id") REFERENCES "chapters" ("id");

ALTER TABLE "lesson_contents" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id");

ALTER TABLE "lesson_content_media_files" ADD FOREIGN KEY ("lesson_content_id") REFERENCES "lesson_contents" ("id");