
CREATE UNIQUE INDEX idx_chapters_order_number ON chapters (order_number, subject_id);

CREATE UNIQUE INDEX idx_lessons_order_number ON lessons (order_number, chapter_id);

CREATE UNIQUE INDEX idx_subjects_name ON subjects (name, school_class_id);

ALTER TABLE chapters
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN created_on TIMESTAMP(6),
    ADD COLUMN last_modified_by VARCHAR(255),
    ADD COLUMN last_modified_on TIMESTAMP(6);

ALTER TABLE lessons
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN created_on TIMESTAMP(6),
    ADD COLUMN last_modified_by VARCHAR(255),
    ADD COLUMN last_modified_on TIMESTAMP(6);

ALTER TABLE subjects
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN created_on TIMESTAMP(6),
    ADD COLUMN last_modified_by VARCHAR(255),
    ADD COLUMN last_modified_on TIMESTAMP(6);

ALTER TABLE school_classes
    ADD COLUMN created_by VARCHAR(255),
    ADD COLUMN created_on TIMESTAMP(6),
    ADD COLUMN last_modified_by VARCHAR(255),
    ADD COLUMN last_modified_on TIMESTAMP(6);

CREATE TABLE lesson_parts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    order_number        INTEGER                                 NOT NULL,
    content             TEXT,
    lesson_id           BIGINT,
    created_by          VARCHAR(255),
    created_on          TIMESTAMP(6),
    last_modified_by    VARCHAR(255),
    last_modified_on    TIMESTAMP(6),
    CONSTRAINT pk_lesson_parts PRIMARY KEY (id)
);

CREATE TABLE lesson_part_media
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lesson_part_id      BIGINT                                  NOT NULL,
    media_id            BIGINT                                  NOT NULL,
    media_url           VARCHAR(255)                            NOT NULL,
    media_type          VARCHAR(50)                             NOT NULL,
    created_by          VARCHAR(255),
    created_on          TIMESTAMP(6),
    last_modified_by    VARCHAR(255),
    last_modified_on    TIMESTAMP(6),
    CONSTRAINT pk_lesson_part_media PRIMARY KEY (id)
);

ALTER TABLE lesson_parts
    ADD CONSTRAINT FK_LESSON_PARTS_ON_LESSON FOREIGN KEY (lesson_id) REFERENCES lessons (id);
