-- LESSON CONTENTS for lesson_id = 1 (Cách mạng công nghiệp)
INSERT INTO lesson_contents (lesson_id, title, order_number, content, is_deleted) VALUES
                                                                                          (1, 'Tổng quan về Cách mạng công nghiệp', 3,
                                                                                           '# Cách mạng công nghiệp là gì?\n\nCách mạng công nghiệp là một bước ngoặt lớn trong lịch sử nhân loại, đánh dấu sự chuyển đổi từ nền sản xuất thủ công sang nền sản xuất bằng máy móc. Quá trình này bắt đầu từ nước Anh vào cuối thế kỷ 18 và nhanh chóng lan rộng khắp châu Âu và thế giới. Nó tạo điều kiện cho sự phát triển mạnh mẽ của chủ nghĩa tư bản và nền kinh tế hiện đại. Những thay đổi về kỹ thuật, sản xuất và tổ chức xã hội đã ảnh hưởng sâu sắc đến mọi lĩnh vực đời sống.', false),

                                                                                          ( 1, 'Nguyên nhân của Cách mạng công nghiệp', 4,
                                                                                           '## Nguyên nhân chính\n\nCách mạng công nghiệp bắt nguồn từ nhiều yếu tố khác nhau. Một trong những nguyên nhân quan trọng là nhu cầu tăng cao về sản phẩm trong xã hội châu Âu, đặc biệt là sau các cuộc cách mạng nông nghiệp. Bên cạnh đó, sự phát triển của khoa học – kỹ thuật và sự tích lũy vốn trong giai cấp tư sản đã tạo điều kiện thuận lợi cho công nghiệp hóa. Ngoài ra, hệ thống thuộc địa rộng lớn cũng cung cấp nguyên liệu và thị trường tiêu thụ quan trọng.', false),

                                                                                          ( 1, 'Diễn biến của Cách mạng công nghiệp', 5,
                                                                                           '## Hai giai đoạn lớn\n\nCách mạng công nghiệp diễn ra qua hai giai đoạn chính. Giai đoạn đầu (thế kỷ 18 – giữa thế kỷ 19) chứng kiến sự phát minh và sử dụng máy móc cơ khí như máy kéo sợi, máy dệt và động cơ hơi nước. Giai đoạn thứ hai (cuối thế kỷ 19 – đầu thế kỷ 20) đánh dấu sự phát triển của các ngành điện, hóa học, thép và giao thông vận tải hiện đại. Những tiến bộ này đã thay đổi hoàn toàn bộ mặt kinh tế và xã hội của các quốc gia công nghiệp.', false),

                                                                                          ( 1, 'Hệ quả kinh tế - xã hội', 6,
                                                                                           '## Tác động của cuộc cách mạng\n\nCách mạng công nghiệp mang lại nhiều tác động tích cực lẫn tiêu cực. Về kinh tế, nó giúp tăng năng suất lao động, hạ giá thành sản phẩm và thúc đẩy giao thương quốc tế. Về xã hội, cách mạng công nghiệp làm xuất hiện giai cấp công nhân và làm thay đổi cấu trúc giai cấp xã hội. Tuy nhiên, nó cũng kéo theo nhiều vấn đề như ô nhiễm môi trường, điều kiện làm việc khắc nghiệt và khoảng cách giàu nghèo ngày càng lớn.', false),

                                                                                          ( 1, 'Ý nghĩa lịch sử', 7,
                                                                                           '## Bước ngoặt quan trọng\n\nCách mạng công nghiệp được coi là cuộc cách mạng vĩ đại thứ hai trong lịch sử nhân loại, sau cuộc cách mạng nông nghiệp. Nó đã phá vỡ những ràng buộc của nền sản xuất phong kiến và mở đường cho nền sản xuất tư bản phát triển. Những thành tựu kỹ thuật đạt được trong thời kỳ này đã tạo nền móng cho các cuộc cách mạng công nghiệp tiếp theo. Từ đó, con người bước vào thời kỳ hiện đại với sự phụ thuộc ngày càng lớn vào máy móc và công nghệ.', false),

                                                                                          ( 1, 'Các phát minh tiêu biểu', 8,
                                                                                           '## Những phát minh làm thay đổi thế giới\n\nNhiều phát minh trong thời kỳ này có vai trò cực kỳ quan trọng. Ví dụ như máy kéo sợi Jenny của James Hargreaves giúp tăng năng suất ngành dệt, còn động cơ hơi nước của James Watt là nền tảng cho giao thông và công nghiệp. Ngoài ra, hệ thống đường sắt và tàu thủy chạy bằng hơi nước đã mở rộng phạm vi thương mại toàn cầu. Những phát minh này không chỉ thúc đẩy sản xuất mà còn làm thay đổi cách con người di chuyển và giao tiếp.', false);
