spring:
  application:
    name: project-service

  kafka:
    producer:
      bootstrap-servers: localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'

  config:
    import: optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
