webclient:
  gateway:
    base-url: ${GATEWAY_SERVICE_URL:http://localhost:8222}
spring:
  application:
    name: project-service
  profiles:
    active: native
  config:
      import: optional:configserver:http://localhost:8888
