CREATE TABLE notifications
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    is_deleted       BOOLEAN                                 NOT NULL,
    type             VARCHAR(255),
    title            VARCHAR(255)                            NOT NULL,
    description      TEXT                                    NOT NULL,
    time             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_read          BOOLEAN DEFAULT FALSE,
    icon_name        VARCHAR(255),
    icon_color_hex   VARCHAR(255),
    user_id          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);