-- V2__create_user_device_tokens.sql
CREATE TABLE user_device_tokens
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id           VARCHAR(255)                            NOT NULL,
    device_id         VARCHAR(255)                            NOT NULL,
    fcm_token         VARCHAR(512)                            NOT NULL UNIQUE,
    device_name       VARCHAR(255),
    platform          VARCHAR(255),
    created_on        TIMESTAMP WITHOUT TIME ZONE,
    last_modified_on  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted        BOOLEAN                                 NOT NULL
);