spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-service
  profiles:
    active: native # Use 'docker' profile to load configurations from the Docker environment
