server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sum2025-swd931-g06/GenEdu-BE-Config-Server
          username: sum2025-swd931-g06
          password: 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
