server:
  port: 8888
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sum2025-swd931-g06/GenEdu-BE-Config-Server
          username: sum2025-swd931-g06
          password: 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
          search-paths: configurations-dev