server:
  port: 8888
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sum2025-swd931-g06/GenEdu-BE-Config-Server
          username: sum2025-swd931-g06
          password: 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
          search-paths: configurations-docker
