services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - /DATA/AppData/genedu/postgres/data:/data/postgres
      - /DATA/AppData/genedu/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    hostname: postgresql
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U "${POSTGRES_USER:-admin}"']
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5434:5432"
    secrets:
      - postgres_password
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - /DATA/AppData/genedu/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    hostname: zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  config-server:
    container_name: config-server
    image: chauvinhtien/genedu-config-server
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env.deployment
    networks:
      - microservices-net

  discovery-service:
    container_name: discovery
    hostname: discovery
    image: chauvinhtien/genedu-discovery
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery:8761/eureka/apps"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8761:8761"
    env_file:
      - .env.deployment
    networks:
      - microservices-net

  gateway-service:
    container_name: gateway
    hostname: gateway
    image: chauvinhtien/genedu-gateway
    ports:
      - "8222:8222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:8222/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env.deployment
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - microservices-net

  content-service:
    container_name: content
    image: chauvinhtien/genedu-content
    hostname: content
    env_file:
      - .env.deployment
    ports:
      - "8091:8091"
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      gateway-service:
        condition: service_healthy

      postgresql:
        condition: service_started
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

secrets:
  postgres_password:
    file: secret.postgres_password.txt
